sonar.projectKey=proof-vscode
sonar.projectName=proof-vscode
sonar.projectVersion=0.0.1

sonar.sources=src
sonar.exclusions=src/test/**,out/**,dist/**,coverage/**,coverage-integration/**
sonar.tests=src/test
sonar.test.inclusions=src/test/**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info,coverage-integration/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info,coverage-integration/lcov.info

sonar.sourceEncoding=UTF-8
